[package]
name = "spike-influx"
version = "0.0.1"
edition = "2021"

[dependencies]
influxdb = "0.7.0"
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.37"
ts_opentelemetry = "0.20.0-beta.1"
